#!/usr/bin/env python3
from operator import methodcaller
from pathlib import Path

import click
import pandas as pd


@click.command("join")
@click.option("--results-dir", type=click.Path(exists=True, file_okay=False, dir_okay=True, readable=True),
              required=True)
@click.option("--column", type=click.Choice(["time_end2end", "nb_atoms"]), required=True)
def main(results_dir: str, column: str):
    results_dir = Path(results_dir)
    columns = []
    data = {}
    result = pd.DataFrame()
    name_column = None
    for tool_dir in filter(methodcaller("is_dir"), results_dir.iterdir()):
        output_tsv_file = tool_dir / "output.tsv"
        df = pd.read_csv(output_tsv_file, sep="\t")
        if name_column is None:
            name_column = df["name"]
            result["name"] = name_column
        result[tool_dir.name] = df[column]
        columns.append(data)

    result.set_index("name", inplace=True)
    print(result)


if __name__ == '__main__':
    main()
